language: python
env:
  global:
  - secure: oDGsjAewUwWe2V3+y+qySeroetwsIYixraWyzjrIByxO+oei4NNm2pHPo36FebVQN02iS0aSh7UAAo5zRTRNCmYNvp+NUyVXKH5LoQHe4GwqRe4dT272+eiWLfxCOX2JZ1IV03l6rkcUCFoHZZ9piIH8ozlSzPY2h4kjbxDx9Wg=
  - secure: LJaSsPJ6uVu3fSHCx+mx0CVODmVHbUnMkOq7YwKKaPa6H+dNo699wqVQ3PwbCPWuJqK7itX+vuMZiIzfeTbsrKw3vKhYETtuUZUsNqwfhj5VMd8F1uDoI9drj25Uwm/1ByIh8b+KOuW7TzE48t+TkWSiU4SL+vI5uMnKEelmcvs=
  - BOB_UPLOAD_WHEEL=1
matrix:
  include:
  - python: 2.6
  - python: 2.7
    env:
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
  - python: 3.3
  - python: 3.4
before_install:
- sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes libboost-all-dev libblitz1-dev libhdf5-serial-dev texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose coverage cpp-coveralls
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- CPPFLAGS=--coverage LDFLAGS=--coverage ./bin/buildout buildout:debug=false buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
- ./bin/python -c 'import pkg_resources; from bob.ip.color import get_config; print(get_config())'
- ./bin/coverage run --source=bob.ip.color ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- cpp-coveralls --build-root=`pwd` --exclude=src --exclude-pattern=".*Compiler.*" --dump=cpp_cov.json
- coveralls --merge=cpp_cov.json
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
